/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  maria
 * Created: 3 May, 2018
 */
insert into sports (sportsitem) values  ('Akademisk ');
insert into sports (sportsitem) values  ('Amerikansk Fotboll');
insert into sports (sportsitem) values  ('Badminton');
insert into sports (sportsitem) values  ('Bandy');
insert into sports (sportsitem) values  ('Bangolf');
insert into sports (sportsitem) values  ('Baseboll och Softboll');
insert into sports (sportsitem) values  ('Basket');
insert into sports (sportsitem) values  ('Biljard');
insert into sports (sportsitem) values  ('Bilsport');
insert into sports (sportsitem) values  ('Bob och Rodel');
insert into sports (sportsitem) values  ('Bordtennis');
insert into sports (sportsitem) values  ('Boule');
insert into sports (sportsitem) values  ('Bowling');
insert into sports (sportsitem) values  ('Boxning');
insert into sports (sportsitem) values  ('Brottning');
insert into sports (sportsitem) values  ('Brottning - Används ej');
insert into sports (sportsitem) values  ('Budo och Kampsport');
insert into sports (sportsitem) values  ('Budo och Kampsport - Aikido');
insert into sports (sportsitem) values  ('Budo och Kampsport - Armsport');
insert into sports (sportsitem) values  ('Budo och Kampsport - Brasiliansk Jiu-Jitsu');
insert into sports (sportsitem) values  ('Budo och Kampsport - Bujinkan');
insert into sports (sportsitem) values  ('Budo och Kampsport - Capoeira');
insert into sports (sportsitem) values  ('Budo och Kampsport - Filippinska Kamparter');
insert into sports (sportsitem) values  ('Budo och Kampsport - Glima');
insert into sports (sportsitem) values  ('Budo och Kampsport - HEMA');
insert into sports (sportsitem) values  ('Budo och Kampsport - Iaido');
insert into sports (sportsitem) values  ('Budo och Kampsport - Jodo');
insert into sports (sportsitem) values  ('Budo och Kampsport - Ju Jutsu');
insert into sports (sportsitem) values  ('Budo och Kampsport - Kendo');
insert into sports (sportsitem) values  ('Budo och Kampsport - Kickboxning');
insert into sports (sportsitem) values  ('Budo och Kampsport - Krav Maga');
insert into sports (sportsitem) values  ('Budo och Kampsport - Kyokushin');
insert into sports (sportsitem) values  ('Budo och Kampsport - Kyudo');
insert into sports (sportsitem) values  ('Budo och Kampsport - Mixed Martial Arts');
insert into sports (sportsitem) values  ('Budo och Kampsport - Muaythai - Thaiboxning');
insert into sports (sportsitem) values  ('Budo och Kampsport - Naginata');
insert into sports (sportsitem) values  ('Budo och Kampsport - Sambo');
insert into sports (sportsitem) values  ('Budo och Kampsport - Savate');
insert into sports (sportsitem) values  ('Budo och Kampsport - Shootfighting');
insert into sports (sportsitem) values  ('Budo och Kampsport - Shorinjikempo');
insert into sports (sportsitem) values  ('Budo och Kampsport - Submission Wrestling');
insert into sports (sportsitem) values  ('Budo och Kampsport - Sumo');
insert into sports (sportsitem) values  ('Budo och Kampsport - Systema');
insert into sports (sportsitem) values  ('Budo och Kampsport - Taido');
insert into sports (sportsitem) values  ('Budo och Kampsport - Wushu');
insert into sports (sportsitem) values  ('Bågskytte');
insert into sports (sportsitem) values  ('Bågskytte - 3D');
insert into sports (sportsitem) values  ('Bågskytte - Arc-Trap');
insert into sports (sportsitem) values  ('Bågskytte - Beridet Bågskytte');
insert into sports (sportsitem) values  ('Bågskytte - Fält');
insert into sports (sportsitem) values  ('Bågskytte - Svensk Jakt');
insert into sports (sportsitem) values  ('Bågskytte - Tavla inne');
insert into sports (sportsitem) values  ('Bågskytte - Tavla ute');
insert into sports (sportsitem) values  ('Casting');
insert into sports (sportsitem) values  ('Cricket');
insert into sports (sportsitem) values  ('Curling');
insert into sports (sportsitem) values  ('Curling - Rullstolscurlare');
insert into sports (sportsitem) values  ('Cykel');
insert into sports (sportsitem) values  ('Cykel - Bancykel');
insert into sports (sportsitem) values  ('Cykel - BMX');
insert into sports (sportsitem) values  ('Cykel - Cykelcross');
insert into sports (sportsitem) values  ('Cykel - Landsväg');
insert into sports (sportsitem) values  ('Cykel - Mountainbike');
insert into sports (sportsitem) values  ('Cykel - Paracykel');
insert into sports (sportsitem) values  ('Cykel - Trial Cykel');
insert into sports (sportsitem) values  ('Danssport');
insert into sports (sportsitem) values  ('Danssport - BRR');
insert into sports (sportsitem) values  ('Danssport - Disco');
insert into sports (sportsitem) values  ('Danssport - Drill');
insert into sports (sportsitem) values  ('Danssport - HipHop');
insert into sports (sportsitem) values  ('Danssport - Linedance');
insert into sports (sportsitem) values  ('Danssport - TIO');
insert into sports (sportsitem) values  ('Dart');
insert into sports (sportsitem) values  ('Draghundsport');
insert into sports (sportsitem) values  ('Dragkamp');
insert into sports (sportsitem) values  ('Dövidrott');
insert into sports (sportsitem) values  ('Flygsport');
insert into sports (sportsitem) values  ('Flygsport - 1');
insert into sports (sportsitem) values  ('Flygsport - Ballongflyg');
insert into sports (sportsitem) values  ('Flygsport - Fallskärmshoppning');
insert into sports (sportsitem) values  ('Flygsport - Hängflyg');
insert into sports (sportsitem) values  ('Flygsport - Konstflyg');
insert into sports (sportsitem) values  ('Flygsport - Modellflyg');
insert into sports (sportsitem) values  ('Flygsport - Motorflyg');
insert into sports (sportsitem) values  ('Flygsport - Multipla Flygsporter');
insert into sports (sportsitem) values  ('Flygsport - Segelflyg');
insert into sports (sportsitem) values  ('Flygsport - Skärmflyg');
insert into sports (sportsitem) values  ('Fotboll');
insert into sports (sportsitem) values  ('Friidrott');
insert into sports (sportsitem) values  ('Frisbee');
insert into sports (sportsitem) values  ('Frisbee - Allround');
insert into sports (sportsitem) values  ('Frisbee - Discgolf');
insert into sports (sportsitem) values  ('Frisbee - Ultimate');
insert into sports (sportsitem) values  ('Fäktning');
insert into sports (sportsitem) values  ('Golf');
insert into sports (sportsitem) values  ('Gymnastik');
insert into sports (sportsitem) values  ('Gymnastik - Aerobic Gymnastics');
insert into sports (sportsitem) values  ('Gymnastik - Bamsegympa');
insert into sports (sportsitem) values  ('Gymnastik - Bamsegympa');
insert into sports (sportsitem) values  ('Gymnastik - Barngymnastik upp till 6 år');
insert into sports (sportsitem) values  ('Gymnastik - Cheerleading');
insert into sports (sportsitem) values  ('Gymnastik - Drill');
insert into sports (sportsitem) values  ('Gymnastik - Familjegymnastik');
insert into sports (sportsitem) values  ('Gymnastik - Gymmix/Gruppträning');
insert into sports (sportsitem) values  ('Gymnastik - Gymmix/Seniorträning över 65 år');
insert into sports (sportsitem) values  ('Gymnastik - Gympa Kidz/Barngymnastik 7-12 år');
insert into sports (sportsitem) values  ('Gymnastik - Hopprep');
insert into sports (sportsitem) values  ('Gymnastik - Kvinnlig Artistisk Gymnastik');
insert into sports (sportsitem) values  ('Gymnastik - Manlig Artistisk Gymnastik');
insert into sports (sportsitem) values  ('Gymnastik - Rytmisk Gymnastik');
insert into sports (sportsitem) values  ('Gymnastik - Trampolin');
insert into sports (sportsitem) values  ('Gymnastik - Truppgymnastik');
insert into sports (sportsitem) values  ('Gymnastik - Ungdomsgymnastik 13-20 år');
insert into sports (sportsitem) values  ('Gång och Vandring');
insert into sports (sportsitem) values  ('Handboll');
insert into sports (sportsitem) values  ('IHR');
insert into sports (sportsitem) values  ('Innebandy');
insert into sports (sportsitem) values  ('Ishockey');
insert into sports (sportsitem) values  ('Islandshäst');
insert into sports (sportsitem) values  ('Issegling');
insert into sports (sportsitem) values  ('Judo');
insert into sports (sportsitem) values  ('Kanot');
insert into sports (sportsitem) values  ('Karate');
insert into sports (sportsitem) values  ('Klättring');
insert into sports (sportsitem) values  ('Konståkning');
insert into sports (sportsitem) values  ('Korpen');
insert into sports (sportsitem) values  ('Korpen - Aerobics');
insert into sports (sportsitem) values  ('Korpen - Afro');
insert into sports (sportsitem) values  ('Korpen - Badminton ( Korpen )');
insert into sports (sportsitem) values  ('Korpen - Bangolf (Korpen)');
insert into sports (sportsitem) values  ('Korpen - Basket ( Korpen )');
insert into sports (sportsitem) values  ('Korpen - Beachvolleyboll (Korpen)');
insert into sports (sportsitem) values  ('Korpen - BMX (Korpen)');
insert into sports (sportsitem) values  ('Korpen - Bordtennis ( Korpen )');
insert into sports (sportsitem) values  ('Korpen - Boule ( Korpen )');
insert into sports (sportsitem) values  ('Korpen - Bowling ( Korpen )');
insert into sports (sportsitem) values  ('Korpen - Box');
insert into sports (sportsitem) values  ('Korpen - Cirkelträning');
insert into sports (sportsitem) values  ('Korpen - Core (rygg/bål)');
insert into sports (sportsitem) values  ('Korpen - Curling (korpen)');
insert into sports (sportsitem) values  ('Korpen - Cykling');
insert into sports (sportsitem) values  ('Korpen - Dans');
insert into sports (sportsitem) values  ('Korpen - Five-a-side');
insert into sports (sportsitem) values  ('Korpen - Fotboll ( Korpen )');
insert into sports (sportsitem) values  ('Korpen - Fotboll (futsal, five a side)');
insert into sports (sportsitem) values  ('Korpen - Fotboll (Korpen)');
insert into sports (sportsitem) values  ('Korpen - Funktionell träning – EFIT');
insert into sports (sportsitem) values  ('Korpen - Futsal');
insert into sports (sportsitem) values  ('Korpen - Föräldrar och barn');
insert into sports (sportsitem) values  ('Korpen - Golf (Korpen)');
insert into sports (sportsitem) values  ('Korpen - Gym');
insert into sports (sportsitem) values  ('Korpen - Gympa');
insert into sports (sportsitem) values  ('Korpen - Handboll (Korpen)');
insert into sports (sportsitem) values  ('Korpen - Handboll ( Korpen )');
insert into sports (sportsitem) values  ('Korpen - Hockeybockey (Korpen)');
insert into sports (sportsitem) values  ('Korpen - Innebandy (Korpen)');
insert into sports (sportsitem) values  ('Korpen - Innebandy ( Korpen )');
insert into sports (sportsitem) values  ('Korpen - Ishockey ( Korpen )');
insert into sports (sportsitem) values  ('Korpen - Kempo');
insert into sports (sportsitem) values  ('Korpen - Kägel');
insert into sports (sportsitem) values  ('Korpen - Löpning');
insert into sports (sportsitem) values  ('Korpen - Paddling (Korpen)');
insert into sports (sportsitem) values  ('Korpen - Parkour');
insert into sports (sportsitem) values  ('Korpen - Pilates');
insert into sports (sportsitem) values  ('Korpen - Pump');
insert into sports (sportsitem) values  ('Korpen - Qi gong');
insert into sports (sportsitem) values  ('Korpen - Racketlon (Korpen)');
insert into sports (sportsitem) values  ('Korpen - Rinkbandy');
insert into sports (sportsitem) values  ('Korpen - Rinkbandy');
insert into sports (sportsitem) values  ('Korpen - Senioraktiviteter');
insert into sports (sportsitem) values  ('Korpen - Skateboard (Korpen)');
insert into sports (sportsitem) values  ('Korpen - Spinning');
insert into sports (sportsitem) values  ('Korpen - Squash ( Korpen )');
insert into sports (sportsitem) values  ('Korpen - Stavgång');
insert into sports (sportsitem) values  ('Korpen - Step');
insert into sports (sportsitem) values  ('Korpen - Streetdance');
insert into sports (sportsitem) values  ('Korpen - Taekwondo (Korpen)');
insert into sports (sportsitem) values  ('Korpen - Tennis ( Korpen )');
insert into sports (sportsitem) values  ('Korpen - Tipspromenad');
insert into sports (sportsitem) values  ('Korpen - Varpa (Korpen)');
insert into sports (sportsitem) values  ('Korpen - Vattenträning');
insert into sports (sportsitem) values  ('Korpen - Volleyboll (Korpen)');
insert into sports (sportsitem) values  ('Korpen - Yoga');
insert into sports (sportsitem) values  ('Korpen - Zumba / Latin moves');
insert into sports (sportsitem) values  ('Landhockey');
insert into sports (sportsitem) values  ('Motorcykel och Snöskoter');
insert into sports (sportsitem) values  ('Motorcykel och Snöskoter - Dragracing');
insert into sports (sportsitem) values  ('Motorcykel och Snöskoter - Enduro');
insert into sports (sportsitem) values  ('Motorcykel och Snöskoter - Flat Track');
insert into sports (sportsitem) values  ('Motorcykel och Snöskoter - Isracing');
insert into sports (sportsitem) values  ('Motorcykel och Snöskoter - Minimoto');
insert into sports (sportsitem) values  ('Motorcykel och Snöskoter - Motocross');
insert into sports (sportsitem) values  ('Motorcykel och Snöskoter - Roadracing');
insert into sports (sportsitem) values  ('Motorcykel och Snöskoter - Snöskoter');
insert into sports (sportsitem) values  ('Motorcykel och Snöskoter - Speedway');
insert into sports (sportsitem) values  ('Motorcykel och Snöskoter - Supermoto');
insert into sports (sportsitem) values  ('Motorcykel och Snöskoter - Trial');
insert into sports (sportsitem) values  ('Mångkamp');
insert into sports (sportsitem) values  ('Mångkamp - Militär femkamp');
insert into sports (sportsitem) values  ('Mångkamp - Modern femkamp');
insert into sports (sportsitem) values  ('Mångkamp - Modern Femkamp & Biathle');
insert into sports (sportsitem) values  ('Mångkamp - Orienteringsskytte');
insert into sports (sportsitem) values  ('Orientering');
insert into sports (sportsitem) values  ('Parasport');
insert into sports (sportsitem) values  ('Parasport - Alpint SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Alpint SHIF/SPK 1');
insert into sports (sportsitem) values  ('Parasport - Boccia');
insert into sports (sportsitem) values  ('Parasport - Boccia SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Bordtennis SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Bänkpress SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Elektronskytte SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Elhockey');
insert into sports (sportsitem) values  ('Parasport - Fotboll SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Friidrott SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Goalball SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Innebandy SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Judo SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Kälkhockey SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Längdskidor/Skidskytte SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Mattcurling SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Rullstolsdans SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Rullstolsrugby SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Showdown SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Simning SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Sportskytte SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Varpa SHIF/SPK');
insert into sports (sportsitem) values  ('Parasport - Volleyboll SHIF/SPK');
insert into sports (sportsitem) values  ('Racerbåt');
insert into sports (sportsitem) values  ('Ridsport');
insert into sports (sportsitem) values  ('Ridsport - Island');
insert into sports (sportsitem) values  ('Ridsport - Islandshäs');
insert into sports (sportsitem) values  ('RIG');
insert into sports (sportsitem) values  ('Ringette');
insert into sports (sportsitem) values  ('Ringette');
insert into sports (sportsitem) values  ('Rodd');
insert into sports (sportsitem) values  ('Rodd - Gymnasier');
insert into sports (sportsitem) values  ('Rodd - Handikapp');
insert into sports (sportsitem) values  ('Rodd - Högskolor');
insert into sports (sportsitem) values  ('Rodd - Inriggare');
insert into sports (sportsitem) values  ('Rodd - Junior');
insert into sports (sportsitem) values  ('Rodd - Kustrodd');
insert into sports (sportsitem) values  ('Rodd - Kyrkbåt');
insert into sports (sportsitem) values  ('Rodd - Långfärd');
insert into sports (sportsitem) values  ('Rodd - Masters');
insert into sports (sportsitem) values  ('Rodd - Motion');
insert into sports (sportsitem) values  ('Rodd - OS-rodd');
insert into sports (sportsitem) values  ('Rodd - Roddmaskin');
insert into sports (sportsitem) values  ('Rodd - Senior');
insert into sports (sportsitem) values  ('Rodd - Tiohuggare');
insert into sports (sportsitem) values  ('Rodd - Vilande');
insert into sports (sportsitem) values  ('Rugby');
insert into sports (sportsitem) values  ('Segling');
insert into sports (sportsitem) values  ('Segling - 2.4mR');
insert into sports (sportsitem) values  ('Segling - 29er');
insert into sports (sportsitem) values  ('Segling - 420');
insert into sports (sportsitem) values  ('Segling - 470');
insert into sports (sportsitem) values  ('Segling - 505');
insert into sports (sportsitem) values  ('Segling - 5m');
insert into sports (sportsitem) values  ('Segling - 606');
insert into sports (sportsitem) values  ('Segling - 6mR');
insert into sports (sportsitem) values  ('Segling - Accent');
insert into sports (sportsitem) values  ('Segling - A-Kat');
insert into sports (sportsitem) values  ('Segling - Albin 78');
insert into sports (sportsitem) values  ('Segling - Ballad');
insert into sports (sportsitem) values  ('Segling - Beneteau');
insert into sports (sportsitem) values  ('Segling - Birdie');
insert into sports (sportsitem) values  ('Segling - C55');
insert into sports (sportsitem) values  ('Segling - Carerra');
insert into sports (sportsitem) values  ('Segling - Catamaran och trimaran');
insert into sports (sportsitem) values  ('Segling - CB66');
insert into sports (sportsitem) values  ('Segling - Comfort Comfortina');
insert into sports (sportsitem) values  ('Segling - Contrast');
insert into sports (sportsitem) values  ('Segling - Cumulus');
insert into sports (sportsitem) values  ('Segling - DF 65');
insert into sports (sportsitem) values  ('Segling - Diva');
insert into sports (sportsitem) values  ('Segling - Drake');
insert into sports (sportsitem) values  ('Segling - E-jolle');
insert into sports (sportsitem) values  ('Segling - Enmeter');
insert into sports (sportsitem) values  ('Segling - Express');
insert into sports (sportsitem) values  ('Segling - F18');
insert into sports (sportsitem) values  ('Segling - Fareast 28R');
insert into sports (sportsitem) values  ('Segling - Farr 30');
insert into sports (sportsitem) values  ('Segling - Finnjolle');
insert into sports (sportsitem) values  ('Segling - Folkbåt');
insert into sports (sportsitem) values  ('Segling - Havskappsegling');
insert into sports (sportsitem) values  ('Segling - H-Båt');
insert into sports (sportsitem) values  ('Segling - Hobie Cat');
insert into sports (sportsitem) values  ('Segling - IF');
insert into sports (sportsitem) values  ('Segling - IRC');
insert into sports (sportsitem) values  ('Segling - IRC');
insert into sports (sportsitem) values  ('Segling - J/105');
insert into sports (sportsitem) values  ('Segling - J/70');
insert into sports (sportsitem) values  ('Segling - J/80');
insert into sports (sportsitem) values  ('Segling - J24');
insert into sports (sportsitem) values  ('Segling - J24 Förbundet');
insert into sports (sportsitem) values  ('Segling - Jolly-Scott');
insert into sports (sportsitem) values  ('Segling - Kite');
insert into sports (sportsitem) values  ('Segling - Kona One');
insert into sports (sportsitem) values  ('Segling - Koster');
insert into sports (sportsitem) values  ('Segling - Lady Hellsman');
insert into sports (sportsitem) values  ('Segling - Laser');
insert into sports (sportsitem) values  ('Segling - Linjett');
insert into sports (sportsitem) values  ('Segling - M32');
insert into sports (sportsitem) values  ('Segling - Marblehead');
insert into sports (sportsitem) values  ('Segling - Maxi 77');
insert into sports (sportsitem) values  ('Segling - Maxi 95');
insert into sports (sportsitem) values  ('Segling - Maxi Racer');
insert into sports (sportsitem) values  ('Segling - M-Båt');
insert into sports (sportsitem) values  ('Segling - Melges 24');
insert into sports (sportsitem) values  ('Segling - Mirror');
insert into sports (sportsitem) values  ('Segling - Moth');
insert into sports (sportsitem) values  ('Segling - Neptunkryssare');
insert into sports (sportsitem) values  ('Segling - NF');
insert into sports (sportsitem) values  ('Segling - Nordisk Kryssare');
insert into sports (sportsitem) values  ('Segling - Nova');
insert into sports (sportsitem) values  ('Segling - OK-Jolle');
insert into sports (sportsitem) values  ('Segling - Omega 42');
insert into sports (sportsitem) values  ('Segling - Optimist');
insert into sports (sportsitem) values  ('Segling - RB 111');
insert into sports (sportsitem) values  ('Segling - RC-Laser');
insert into sports (sportsitem) values  ('Segling - Rival 22');
insert into sports (sportsitem) values  ('Segling - RJ 85');
insert into sports (sportsitem) values  ('Segling - RS 200');
insert into sports (sportsitem) values  ('Segling - RS 500');
insert into sports (sportsitem) values  ('Segling - RS Feva');
insert into sports (sportsitem) values  ('Segling - RS Tera');
insert into sports (sportsitem) values  ('Segling - S 30');
insert into sports (sportsitem) values  ('Segling - Safir');
insert into sports (sportsitem) values  ('Segling - Scampi');
insert into sports (sportsitem) values  ('Segling - Scanner-Skanmar');
insert into sports (sportsitem) values  ('Segling - Seglng');
insert into sports (sportsitem) values  ('Segling - Shipman 28');
insert into sports (sportsitem) values  ('Segling - Skippi 650 C');
insert into sports (sportsitem) values  ('Segling - Skärgårdskryssare');
insert into sports (sportsitem) values  ('Segling - Smaragd');
insert into sports (sportsitem) values  ('Segling - Snipe');
insert into sports (sportsitem) values  ('Segling - Soling');
insert into sports (sportsitem) values  ('Segling - Starbåt');
insert into sports (sportsitem) values  ('Segling - Sveakryssare');
insert into sports (sportsitem) values  ('Segling - Tornado');
insert into sports (sportsitem) values  ('Segling - Triss');
insert into sports (sportsitem) values  ('Segling - Tvåkrona');
insert into sports (sportsitem) values  ('Segling - Vega');
insert into sports (sportsitem) values  ('Segling - Weta 4.4');
insert into sports (sportsitem) values  ('Segling - Viggen');
insert into sports (sportsitem) values  ('Segling - Vindsurfing');
insert into sports (sportsitem) values  ('Segling - X-35');
insert into sports (sportsitem) values  ('Segling - X-35');
insert into sports (sportsitem) values  ('Segling - X99');
insert into sports (sportsitem) values  ('Segling - Yngling');
insert into sports (sportsitem) values  ('Segling - Zoom8');
insert into sports (sportsitem) values  ('Simidrott');
insert into sports (sportsitem) values  ('Skateboard');
insert into sports (sportsitem) values  ('Skidor');
insert into sports (sportsitem) values  ('Skidor - Alpint');
insert into sports (sportsitem) values  ('Skidor - arrangör region 3');
insert into sports (sportsitem) values  ('Skidor - Backhoppning');
insert into sports (sportsitem) values  ('Skidor - Längdåkning');
insert into sports (sportsitem) values  ('Skidor - Nordisk kombination');
insert into sports (sportsitem) values  ('Skidor - Puckel');
insert into sports (sportsitem) values  ('Skidor - Rullskidor');
insert into sports (sportsitem) values  ('Skidor - Skicross');
insert into sports (sportsitem) values  ('Skidor - Skidorientering');
insert into sports (sportsitem) values  ('Skidor - Slopestyle');
insert into sports (sportsitem) values  ('Skidor - Snowboard');
insert into sports (sportsitem) values  ('Skidor - Speedski');
insert into sports (sportsitem) values  ('Skidor - Telemark');
insert into sports (sportsitem) values  ('Skidor - Ungdomsrådet');
insert into sports (sportsitem) values  ('Skidskytte');
insert into sports (sportsitem) values  ('Skolidrott');
insert into sports (sportsitem) values  ('Skridsko');
insert into sports (sportsitem) values  ('Skyttesport');
insert into sports (sportsitem) values  ('Skyttesport - Field Target');
insert into sports (sportsitem) values  ('Skyttesport - Gevär');
insert into sports (sportsitem) values  ('Skyttesport - Lerduva');
insert into sports (sportsitem) values  ('Skyttesport - Pistol');
insert into sports (sportsitem) values  ('Skyttesport - Viltmål');
insert into sports (sportsitem) values  ('Sportdykning');
insert into sports (sportsitem) values  ('Sportdykning - fridykning');
insert into sports (sportsitem) values  ('Squash');
insert into sports (sportsitem) values  ('Styrkelyft');
insert into sports (sportsitem) values  ('Taekwondo');
insert into sports (sportsitem) values  ('Taekwondo - Hapkido');
insert into sports (sportsitem) values  ('Taekwondo - ITF-Taekwondo');
insert into sports (sportsitem) values  ('Taekwondo - WTF-Taekwondo');
insert into sports (sportsitem) values  ('Tennis');
insert into sports (sportsitem) values  ('Triathlon');
insert into sports (sportsitem) values  ('Tyngdlyftning');
insert into sports (sportsitem) values  ('Varpa');
insert into sports (sportsitem) values  ('Vattenskidor och Wakeboard');
insert into sports (sportsitem) values  ('Volleyboll');


insert into region(regionname) values('Västra Götalands län');
insert into region(regionname) values('Kronobergs län');
insert into region(regionname) values('Jönköpings län');
insert into region(regionname) values('Västmanlands län');
insert into region(regionname) values('Norrbottens län');
insert into region(regionname) values('Värmlands län');
insert into region(regionname) values('Örebro län');
insert into region(regionname) values('Dalarnas län');
insert into region(regionname) values('Jämtlands län');
insert into region(regionname) values('Västerbottens län');
insert into region(regionname) values('Skåne län');
insert into region(regionname) values('Gävleborgs län');
insert into region(regionname) values('Kalmar län');
insert into region(regionname) values('Stockholms län');
insert into region(regionname) values('Östergötlands län');
insert into region(regionname) values('Uppsala län');
insert into region(regionname) values('Södermanlands län');
insert into region(regionname) values('Hallands län');
insert into region(regionname) values('Gotlands län');
insert into region(regionname) values('Västernorrlands län');
insert into region(regionname) values('Blekinge län');

insert into clubdetails(OrgNumber,clubname,clubemail,clubpwd,clubphone,clubwebsite) 
values('Org1','club1','club1@sportsclub.com','club1','076543990','www.club1.com');
insert into clubdetails(OrgNumber,clubname,clubemail,clubpwd,clubphone,clubwebsite) 
values('Org2','club2','club2@sportsclub.com','club2','076543991','www.club2.com');
insert into clubdetails(OrgNumber,clubname,clubemail,clubpwd,clubphone,clubwebsite) 
values('Org3','club3','club3@sportsclub.com','club3','076543992','www.club3.com');
insert into clubdetails(OrgNumber,clubname,clubemail,clubpwd,clubphone,clubwebsite) 
values('Org4','club4','club4@sportsclub.com','club4','076543993','www.club4.com');
insert into clubdetails(OrgNumber,clubname,clubemail,clubpwd,clubphone,clubwebsite) 
values('Org5','club5','club5@sportsclub.com','club5','076543994','www.club5.com');


insert into age(agemin,agemax) values(3,7);
insert into age(agemin,agemax) values(8,12);
insert into age(agemin,agemax) values(13,15);
insert into age(agemin,agemax) values(16,18);
insert into age(agemin,agemax) values(19,45);